---
title: "Max Diff Survey"
format: html
editor: visual
---

## This survey is designed to identify the most and least important features while buying a used car.

This survey will take about **10 minutes** to complete. Likewise, it can be stopped and picked up at any time. Your personal information will be kept private and won't be shared with anyone else.

This survey consists of 3 sections:

-   Section 1 - Vehicle Information
-   Section 2 - Demographic Information
-   Section 3 - Knowledge section & Best Worst features

If you have any questions, you can reach out to us at [gwuvehicle\@gmail.com](mailto:gwuvehicle@gmail.com). We will respond at our first convenience. The Office of Human Research of George Washington University, at telephone number (202) 994-2715, can provide further information about your rights as a research participant.

The survey proceeds upon clicking the **"Let's Continue"** button below. We greatly appreciate your participation!

## Section 1: Vehicle Information

### 1(a) Current Vehicle:

-   What is the make and model of your current vehicle?

-   What was the down payment you made for your vehicle?

-   What is your monthly payment?

-   What gas mileage does your vehicle give?

-   How many miles do you drive per week?

-   How many cars do you currently have in your household?

    -   1
    -   2
    -   3 or more
    -   Prefer not to say

-   What type of cars do you have in your household?

    -   Gasoline
    -   Hybrid
    -   Plug-in Hybrid
    -   Electric
    -   Other:

-   Where can you park at home? (Select all that apply)

    -   Street Parking
    -   Driveway/ Carport
    -   Single-family garage
    -   Shared parking garage
    -   Shared parking lot
    -   Prefer not to say
    -   Other:

-   Do any of your neighbors own/lease a plug-in hybrid or pure electric vehicle (Select one)

    -   Yes
    -   No
    -   I'm not sure

### 1(b) Future Vehicle:

-   When are you planning to buy your next vehicle?

-   When you are ready to buy your next car, will you be shopping for new or used vehicles?

    -   New
    -   Used
    -   Both
    -   I'm not sure

-   Will you plan to lease or buy?

    -   Lease
    -   Purchase
    -   I'm not sure

-   What car type(s) will you be shopping for? (Select all that apply)

    -   Hatchback
    -   Sedan
    -   SUV
    -   Truck
    -   Minivan
    -   Other:

-   What is your maximum budget for your next car purchase?

-   What will be your down payment for your next car?

-   Would you consider a Plug-in Hybrid Electric vehicle as your next vehicle?

    -   Definitely not
    -   Probably not
    -   Maybe/ Not sure
    -   Probably Yes

## Section 2: Demographic Information

-   In what year were you born?

    -   Select Year 1920-2003
    -   Prefer not to say

-   What gender do you identify with?

    -   Female
    -   Male
    -   Non-binary
    -   Prefer not to say
    -   Other:

-   I identify my ethnicity as:(select all that apply):

    -   Asian
    -   Black/African
    -   White
    -   Hispanic/Latinx
    -   Native American
    -   Pacific Islander
    -   Prefer not to say
    -   Other:

-   What is the highest degree or level of school you have completed? If currently enrolled, please use the highest degree received.

    -   Less than a high school diploma
    -   High school degree or equivalent(e.g. GED)
    -   Some college or university, no college degree
    -   Trade/technical/vocational training, no degree awarded
    -   Associate degree(e.g. AA, AS)
    -   Bachelor's degree(e.g. BA, BS)
    -   Master's degree(e.g. MA, MS, MEd)
    -   Professional degree(e.g. MD, DDS, DVM)
    -   Doctorate (e.g. PhD, EdD)
    -   Prefer not to say

-   Which of the following categories best describes your current employment status?

    -   I am a full time student.
    -   Employed, working 1-39 hours per week.
    -   Employed, working 40 or more hours per week.
    -   Not employed, looking for work.
    -   Not employed, NOT looking for work.
    -   Retired.
    -   Disabled, not able to work.
    -   Prefer not to say

-   What is your household annual income?

    -   Less than \$10,000
    -   \$10,000 - \$14,999
    -   \$15,000 - \$19,999
    -   \$20,000 - \$24,999
    -   \$25,000 - \$29,999
    -   \$30,000 - \$34,999
    -   \$35,000 - \$39,999
    -   \$40,000 - \$44,999
    -   \$45,000 - \$49,999
    -   \$50,000 - \$54,999
    -   \$55,000 - \$59,999
    -   \$60,000 - \$69,999
    -   \$70,000 - \$79,999
    -   \$80,000 - \$89,999
    -   \$90,000 - \$99,999
    -   More than 100,000
    -   Prefer not to say

-   In which type of housing do you currently live?

    -   Detached house / single family home
    -   Attached house / (townhouse/duplex/triplex)
    -   Condominium
    -   Apartment Building
    -   Mobile Home
    -   Prefer not to say
    -   Other:

-   Do you own or rent your current residence?

    -   Own
    -   Rent
    -   Prefer not to say
    -   Other:

-   What is your monthly electricity bill?

-   How many people live in your household?

    -   1
    -   2
    -   3
    -   4
    -   5 or more
    -   Prefer not to say

-   How would you describe your political views?

    -   Very conservative
    -   Conservative
    -   Moderate
    -   Liberal
    -   Very Liberal
    -   Prefer not to say
    -   Other:

## Section3 : Knowledge section & Best Worst features

### 3 (a) Knowledge Section:

-   Please select which vehicle(s) can run on gasoline: (select all that apply)

    -   Hybrid Electric Vehicle
    -   Plug-in Hybrid Electric Vehicle
    -   Pure Electric Vehicle

-   Please select which vehicles can be plugged-in: (Select all that apply)

    -   Hybrid Electric Vehicle
    -   Plug-in Hybrid Electric Vehicle
    -   Pure Electric Vehicle

-   Do you know the current maximum subsidy available from the US federal government for purchasing an electric vehicle?

    -   \$1,000
    -   \$2,500
    -   \$5,000
    -   \$7,500
    -   \$10,000
    -   I'm not sure

### 3 (b) List of used car features shown for Best Worst Features:

1.  Certified Pre-Owned (CPO) Vehicle

2.  Brand/Vehicle Reputation.

3.  Service Records.

4.  Previous Ownership/s of the vehicle

5.  Vehicle History Report

6.  Where was the vehicle bought/used ?

7.  Vehicle warranty

8.  Customer satisfaction return window

9.  Vehicle Owner manual availability

10. Availability of spare tires and jacking tools

11. Pre-approved loan for the vehicle

12. Pre-purchase independent inspection

13. Test Driving the vehicle

14. Cost of vehicle

15. Mileage on the vehicle

16. What mileage does the vehicle give?

17. Vehicle Capacity

18. Options and features

19. Resale Value

20. Insurance costs
